### ISSUE TITLE
Consider decreasing newness of R version dependency

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1208]
See https://ateucher.shinyapps.io/check_r_versions_of_package_dependencies/

Looks like if we drop **tm** and **slam** from Suggests: then we can make quanteda compatible with older R versions.

@conjugateprior will like this one.

**Comment by juliasilge** [comment]
I have been working on keeping tidytext compatible with older R versions and am currently mostly successful, even with **tm**, **stm**, and some other packages with higher R versioning in Suggests. Here is what I did.

- For any tests and examples, do a `[require("tm", quietly = TRUE)](https://github.com/juliasilge/tidytext/blob/5f0a0e328045b909919f06cd07b039a0f7f7a6b7/tests/testthat/test-stm-tidiers.R#L5)`. ([Another example](https://github.com/juliasilge/tidytext/blob/5f0a0e328045b909919f06cd07b039a0f7f7a6b7/R/corpus_tidiers.R#L20).)
- For vignettes, tell knitr [not to evaluate chunks if it doesn't have what it needs](https://github.com/juliasilge/tidytext/blob/master/vignettes/tidying_casting.Rmd).
- On Travis CI, test on [release and oldrel, but do NOT force the Suggests](https://github.com/juliasilge/tidytext/blob/5f0a0e328045b909919f06cd07b039a0f7f7a6b7/.travis.yml#L6), because they are not all available.

With these options, I have gotten tidytext to pass on Travis [on release and oldrel](https://travis-ci.org/juliasilge/tidytext), which is great! I will admit that I am still failing on [oldrel on CRAN](https://cran.r-project.org/web/checks/check_results_tidytext.html), though, which is a bit mysterious to me. It is because of some quanteda-related functions, which is what leads me to hope that we can get quanteda requiring an older version of R. I am very open to putting together a PR but realistically it will be a week or two before I can sit down with it (I'm not so familiar with the innards of quanteda) so if anyone else beats me to it, that would be amazing. 🙌

**Comment by kbenoit** [comment]
Thanks @juliasilge, we will do our best to scale back the R version requirement based on these clear suggestions. 

Although it's heartbreaking to imagine the Dickensian conditions that would limit someone from running a version of R two years old or more. 😢

**Comment by juliasilge** [comment]
😂😂😂 I know, right? The users who have reached out to me are either a) teaching at universities in computer labs or b) in really big enterprise companies and don't have much freedom to update software on the computers they work on.

**Comment by koheiw** [comment]
This is the list of dependencies:
```
quanteda: R (>= 3.4.0)
  extrafont: R (>= 2.15)
    extrafontdb: R (>= 2.14)
    Rttf2pt1: R (>= 2.15)
  digest: R (>= 2.4.1)
  Matrix: R (>= 3.0.1)
    lattice: R (>= 3.0.0)
  data.table: R (>= 3.0.0)
  wordcloud: 
    RColorBrewer: R (>= 2.0.0)
    slam: R (>= 3.4.0)
    Rcpp: R (>= 3.0.0)
  sna: R (>= 2.0.0)
  network: R (>= 2.10)
  ggrepel: R (>= 3.0.0)
    ggplot2: R (>= 3.1)
      digest: R (>= 2.4.1)
      gtable: R (>= 2.14)
      MASS: R (>= 3.1.0)
      plyr: R (>= 3.1.0)
        Rcpp: R (>= 3.0.0)
      reshape2: R (>= 3.1)
        plyr: R (>= 3.1.0)
          Rcpp: R (>= 3.0.0)
        Rcpp: R (>= 3.0.0)
        stringr: R (>= 2.14)
          stringi: R (>= 2.14)
      scales: R (>= 2.13)
        RColorBrewer: R (>= 2.0.0)
        dichromat: R (>= 2.10)
        plyr: R (>= 3.1.0)
          Rcpp: R (>= 3.0.0)
        Rcpp: R (>= 3.0.0)
        R6: R (>= 3.0)
        viridisLite: R (>= 2.10)
      tibble: R (>= 3.1.0)
        cli: R (>= 2.10)
        rlang: R (>= 3.1.0)
      lazyeval: R (>= 3.1.0)
    Rcpp: R (>= 3.0.0)
    scales: R (>= 2.13)
      RColorBrewer: R (>= 2.0.0)
      dichromat: R (>= 2.10)
      plyr: R (>= 3.1.0)
        Rcpp: R (>= 3.0.0)
      Rcpp: R (>= 3.0.0)
      R6: R (>= 3.0)
      viridisLite: R (>= 2.10)
  Rcpp: R (>= 3.0.0)
  RcppParallel: R (>= 3.0.2)
  RSpectra: R (>= 3.0.2)
    Matrix: R (>= 3.0.1)
      lattice: R (>= 3.0.0)
    Rcpp: R (>= 3.0.0)
  stringi: R (>= 2.14)
  ggplot2: R (>= 3.1)
    digest: R (>= 2.4.1)
    gtable: R (>= 2.14)
    MASS: R (>= 3.1.0)
    plyr: R (>= 3.1.0)
      Rcpp: R (>= 3.0.0)
    reshape2: R (>= 3.1)
      plyr: R (>= 3.1.0)
        Rcpp: R (>= 3.0.0)
      Rcpp: R (>= 3.0.0)
      stringr: R (>= 2.14)
        stringi: R (>= 2.14)
    scales: R (>= 2.13)
      RColorBrewer: R (>= 2.0.0)
      dichromat: R (>= 2.10)
      plyr: R (>= 3.1.0)
        Rcpp: R (>= 3.0.0)
      Rcpp: R (>= 3.0.0)
      R6: R (>= 3.0)
      viridisLite: R (>= 2.10)
    tibble: R (>= 3.1.0)
      cli: R (>= 2.10)
      rlang: R (>= 3.1.0)
    lazyeval: R (>= 3.1.0)
  XML: R (>= 2.13.0)
  lubridate: R (>= 3.0.0)
    stringr: R (>= 2.14)
      stringi: R (>= 2.14)
    Rcpp: R (>= 3.0.0)
  spacyr: R (>= 3.3.0)
    data.table: R (>= 3.0.0)
    reticulate: R (>= 3.0)
      jsonlite: 
      Rcpp: R (>= 3.0.0)
  stopwords: R (>= 2.10)
    ISOcodes: R (>= 2.10.0)
```
If we drop **slam** (and wordcloud) and **spacyr**, we can lower our system requirement to R (>= 3.1.0).
